package(default_visibility = ["//visibility:public"])

load("/build_tools/iverilog", "v_binary")

v_binary(
    name = "counter_tb",
    srcs = [
         "counter.v",
         "counter_tb.v",
    ],
)
